// packages/ui/src/react/components/motion/FadeIn.tsx
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { get } from 'lodash-es';
import React, { type FC } from 'react';

import { type FadePropsOptions, createFadeProps } from '../../../lib';

export type FadeInProps<T extends React.ElementType = 'div'> = Omit<
  FadePropsOptions,
  'as'
> & {
  as?: T extends React.ElementType ? T : never;
} & React.ComponentProps<T>;

export function FadeIn<T extends React.ElementType>(
  props: FadeInProps<T>,
): React.ReactNode {
  const { as, tag, ...restProps } = props;
  const shouldReduceMotion = useReducedMotion();

  const Component: FC =
    typeof tag === 'function' ? tag : get(motion, [as ?? 'div']);

  return (
    <AnimatePresence>
      <Component
        as={as}
        {...props}
        {...createFadeProps({
          ...restProps,
          shouldReduceMotion,
        })}
      />
    </AnimatePresence>
  );
}

// packages/ui/src/vue/components/motion/FadeIn.vue
<template>
  <AnimatePresence>
    <component :is="FadeInElement" v-bind="allProps">
      <slot />
    </component>
  </AnimatePresence>
</template>

<script setup lang="ts">
import { get } from 'lodash-es';
import { AnimatePresence, motion, useReducedMotion } from 'motion-v';
import { computed, toRefs, useAttrs } from 'vue';

import { type FadePropsOptions, createFadeProps } from '../../../lib';

export type FadeInProps<T extends keyof HTMLElementTagNameMap = 'div'> = Omit<
  FadePropsOptions,
  'tag'
> & {
  tag?: T | typeof motion;
};

const props = defineProps<FadeInProps>();
const additionalAttributes = useAttrs();
const { tag, as, ...rest } = toRefs(props);

const shouldReduceMotion = useReducedMotion();

const FadeInElement =
  typeof tag.value === 'object'
    ? tag.value
    : get(motion, [as.value ?? 'div'], 'div');

const allProps = computed(() => {
  return {
    ...rest,
    ...additionalAttributes,
    ...createFadeProps({
      ...props,
      shouldReduceMotion: shouldReduceMotion.value,
    } as FadeInProps),
  };
});
</script>
