// packages/ui/src/vue/components/Button/Button.vue
<template>
  <MotionElement
    :class="mergedClass"
    v-bind="buttonProps as Record<string, unknown>"
  >
    <slot />
  </MotionElement>
</template>

<script lang="ts" setup>
import { get } from 'lodash-es';
import { motion } from 'motion-v';
import { twMerge } from 'tailwind-merge';
import { computed, useAttrs } from 'vue';

import {
  buttonStyles,
  composeAnimationProps,
  createA11yButtonProps,
  cursorStyles,
} from '../../../lib';
import { ButtonProps } from './types';

const buttonPropsAttributes = useAttrs() as ButtonProps;

const MotionElement = get(motion, ['button']);

const mergedClass = computed(() =>
  twMerge(
    buttonStyles(buttonPropsAttributes),
    cursorStyles(buttonPropsAttributes),
    buttonPropsAttributes.class,
  ),
);

const buttonProps = computed(() => ({
  ...createA11yButtonProps(buttonPropsAttributes),
  ...composeAnimationProps(buttonPropsAttributes),
}));
</script>

// packages/ui/src/react/components/common/Button.tsx
import { useButton } from '@react-aria/button';
import { type HTMLMotionProps } from 'framer-motion';
import { get } from 'lodash-es';
import React from 'react';
import { twMerge } from 'tailwind-merge';

import {
  type ButtonProps as ButtonPropsBase,
  buttonStyles,
  composeAnimationProps,
  cursorStyles,
} from '../../../lib';
import { MotionElement } from '../motion';

export type ButtonProps = React.PropsWithChildren<ButtonPropsBase>;

export function Button(props: ButtonProps): React.ReactNode {
  const ref = React.useRef(null);

  const { buttonProps } = useButton(props, ref);
  return (
    <MotionElement
      as='button'
      className={twMerge(buttonStyles(props), cursorStyles<ButtonProps>(props))}
      ref={ref}
      type={get(props, ['type'], 'button')}
      {...(buttonProps as unknown as HTMLMotionProps<'button'>)}
      {...composeAnimationProps(props)}
    >
      {props.children}
    </MotionElement>
  );
}

Button.displayName = 'Button';
