// packages/ui/src/vue/components/Avatar/Avatar.vue
<template>
  <MotionElement :class="mergedClass" v-bind="props">
    <slot />
  </MotionElement>
</template>

<script lang="ts" setup>
import { get } from 'lodash-es';
import { motion } from 'motion-v';
import { twMerge } from 'tailwind-merge';
import { computed } from 'vue';

import { avatarStyles } from '../../../lib';
import { AvatarProps } from './types';

const props = defineProps<AvatarProps>();

const MotionElement = get(motion, ['img']);

const mergedClass = computed(() => twMerge(avatarStyles(props), props.class));
</script>

// packages/ui/src/react/components/Avatar/Avatar.tsx
import { type HTMLMotionProps } from 'motion/react';
import React from 'react';
import { twMerge } from 'tailwind-merge';

import {
  type AvatarProps as AvatarPropsBase,
  avatarStyles,
} from '../../../lib';
import { MotionElement } from '../motion';

export type AvatarProps = HTMLMotionProps<'img'> & AvatarPropsBase;

export function Avatar(props: AvatarProps): React.ReactNode {
  return (
    <MotionElement
      as='img'
      {...props}
      className={twMerge(avatarStyles(props), props.className)}
      src={props.src}
      alt={props.alt}
    />
  );
}
