// packages/ui/src/vue/components/Grid/Grid.vue
<template>
  <MotionElement :class="mergedClass" v-bind="modeledProps">
    <slot />
  </MotionElement>
</template>

<script lang="ts" setup>
import { PropertyPath, get } from 'lodash-es';
import { motion } from 'motion-v';
import { twMerge } from 'tailwind-merge';
import { computed, defineProps } from 'vue';

import { composeAnimationProps, modelGridLayout } from '../../../lib';
import { GridProps } from './types';

const props = defineProps<GridProps>();

const MotionElement = get(motion, [props.tag] as PropertyPath);

const mergedClass = computed(() =>
  twMerge(modelGridLayout(props), props.class),
);

const modeledProps = computed(() => ({
  ...props,
  ...composeAnimationProps(props),
}));
</script>

// packages/ui/src/react/components/Grid/Grid.tsx
import React from 'react';
import { twMerge } from 'tailwind-merge';

import {
  type GridComponentProps,
  composeAnimationProps,
  modelGridLayout,
} from '../../../lib';
import { MotionElement } from '../motion';

export type GridProps = React.PropsWithChildren<
  GridComponentProps & { className?: string }
>;

export function Grid(props: GridProps): React.ReactNode {
  const { className, children, ...rest } = props;

  return (
    <MotionElement
      as={rest.tag}
      className={twMerge(modelGridLayout(props), className)}
      {...composeAnimationProps(rest)}
    >
      {children}
    </MotionElement>
  );
}
