// packages/ui/src/react/components/Typography/Typography.tsx
import { get } from 'lodash-es';
import React from 'react';
import { twMerge } from 'tailwind-merge';

import {
  type TypographyComponentLayoutOptions,
  composeAnimationProps,
  modelTypography,
} from '../../../lib';
import { MotionElement } from '../motion';

export type TypographyProps = React.PropsWithChildren<
  TypographyComponentLayoutOptions & { className?: string }
>;

export function Typography(props: TypographyProps): React.ReactNode {
  const { className, children, ...rest } = props;

  return (
    <MotionElement
      as={get(rest, ['tag'], 'p')}
      className={twMerge(modelTypography(props), className)}
      {...composeAnimationProps(rest)}
    >
      {children}
    </MotionElement>
  );
}

// packages/ui/src/vue/components/Typgraphy/Typography.vue
<template>
  <MotionElement :class="mergedClass" v-bind="typographyProps">
    <slot />
  </MotionElement>
</template>

<script lang="ts" setup>
import { get } from 'lodash-es';
import { motion } from 'motion-v';
import { twMerge } from 'tailwind-merge';
import { computed, useAttrs } from 'vue';

import { composeAnimationProps, modelTypography } from '../../../lib';
import { TypographyProps } from './types';

const inputPropsAttributes = useAttrs() as TypographyProps;

const tag = computed(() => get(inputPropsAttributes, ['tag'], 'p'));

const MotionElement = get(motion, [tag.value]);

const mergedClass = computed(() =>
  twMerge(modelTypography(inputPropsAttributes), inputPropsAttributes.class),
);

const typographyProps = computed(() => ({
  ...inputPropsAttributes,
  ...composeAnimationProps(inputPropsAttributes),
}));
</script>
