// packages/ui/src/react/components/Input/Input.tsx
import React from 'react';
import { twMerge } from 'tailwind-merge';

import {
  type InputProps,
  composeAnimationProps,
  cursorStyles,
  inputStyles,
} from '../../../lib';
import { MotionElement } from '../motion';

export function Input(props: InputProps): React.ReactNode {
  return (
    <MotionElement
      as='input'
      {...composeAnimationProps(props)}
      {...props}
      className={twMerge(
        inputStyles(props),
        cursorStyles(props),
        props.className,
      )}
    />
  );
}

// packages/ui/src/vue/components/Input/Input.vue
<template>
  <MotionInput :class="mergedClass" v-bind="$attrs" />
</template>

<script lang="ts" setup>
import { get } from 'lodash-es';
import { motion } from 'motion-v';
import { twMerge } from 'tailwind-merge';
import { computed, useAttrs } from 'vue';

import { cursorStyles, inputStyles } from '../../../lib';

const MotionInput = get(motion, ['input']);

const inputPropsAttributes = useAttrs();

const mergedClass = computed(() =>
  twMerge(
    inputStyles(inputPropsAttributes),
    cursorStyles(inputPropsAttributes),
    get(inputPropsAttributes, ['className']) as string | undefined,
  ),
);
</script>
