// packages/ui/src/vue/context/ThemeProvider.vue
<template>
  <slot />
</template>

<script setup lang="ts">
import { set } from 'lodash-es';
import { onBeforeUnmount, onMounted, provide, ref, toRefs } from 'vue';

import {
  type Theme,
  type ThemeProviderProps,
  ThemeProviderSymbol,
  composeDesignSystem,
  composeThemeProvider,
} from 'src/lib';

const props = defineProps<{
  theme: Theme;
}>();

const { theme } = toRefs(props);

const themeProvider = composeThemeProvider();

const styleElRef = ref<HTMLStyleElement | null>(null);

const cssVariablesMap = ref<Record<string, unknown>>(
  composeDesignSystem(theme.value).cssVariables,
);

function handleVariablesMap(cssVariablesPayload: Record<string, unknown>) {
  styleElRef.value = themeProvider.handleVariablesMap(
    styleElRef.value,
    cssVariablesPayload,
  );
}

function toggleLightDarkTheme() {
  themeProvider.handleToggleLightDarkTheme();
}

function setThemeVariable(variableName: string, variableValue: string) {
  const payload = themeProvider.handleSetThemeVariable({
    variableName,
    variableValue,
  });
  if (payload) {
    set(cssVariablesMap.value, [payload.variableName], payload.variableValue);
    handleVariablesMap(cssVariablesMap.value);
  }
}

const providerValue: ThemeProviderProps = {
  setTheme: handleVariablesMap,
  setThemeVariable,
  toggleLightDarkTheme,
};

provide(ThemeProviderSymbol, providerValue);

onMounted(() => {
  handleVariablesMap(cssVariablesMap?.value);
});

onBeforeUnmount(() => {
  styleElRef.value?.remove();
  styleElRef.value = null;
});
</script>

// packages/ui/src/context/ThemeProvider.tsx
import React, {
  type ReactNode,
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
} from 'react';

import { composeDesignSystemTheme } from '../domain/theme';

interface ThemeProps {
  theme: Record<string, unknown>;
  children?: React.ReactNode;
}

interface ThemeProviderProps {
  setTheme: (theme: Record<string, unknown>) => void;
  setThemeVariable: (variableName: string, variableValue: string) => void;
  toggleLightDarkTheme: () => void;
}

const ThemeContext = createContext<ThemeProviderProps>({
  setThemeVariable: () => {},
  toggleLightDarkTheme: () => {},
  setTheme: () => {},
});

export function ThemeProvider({ theme, children }: ThemeProps): ReactNode {
  const styleElRef = useRef<HTMLStyleElement | null>(null);
  const root = document.documentElement;

  const cssVariablesMap: Record<string, unknown> = useMemo(() => {
    const { cssVariables } = composeDesignSystemTheme(theme);
    return cssVariables;
  }, [theme]);

  const handleVariablesMap = useCallback(
    (cssVariablesPayload: Record<string, unknown>) => {
      if (!styleElRef.current) {
        styleElRef.current = document.createElement('style');
        document.head.appendChild(styleElRef.current);
      }

      styleElRef.current.textContent = `:root {
        ${Object.entries(cssVariablesPayload)
          .map(([variableName, variableValue]) =>
            typeof variableValue === 'string'
              ? `${variableName}: ${variableValue};`
              : '',
          )
          .join('\n')}
      }`;
    },
    [],
  );

  const toggleLightDarkTheme: ThemeProviderProps['toggleLightDarkTheme'] =
    useCallback(() => {
      const selectedMode = root.classList.contains('dark');
      root.classList.toggle('dark', !selectedMode);
    }, [root.classList]);

  const setThemeVariable: ThemeProviderProps['setThemeVariable'] = useCallback(
    (variableName, variableValue) => {
      const styles = getComputedStyle(root);
      const cssVariableValue = styles.getPropertyValue(variableName);

      if (!cssVariableValue.trim().length) return;

      cssVariablesMap[variableName] = variableValue;
      handleVariablesMap(cssVariablesMap);
    },
    [cssVariablesMap, handleVariablesMap, root],
  );

  const providerValue: ThemeProviderProps = useMemo(
    () => ({
      setTheme: handleVariablesMap,
      setThemeVariable,
      toggleLightDarkTheme,
    }),
    [setThemeVariable, handleVariablesMap, toggleLightDarkTheme],
  );

  useEffect(() => {
    handleVariablesMap(cssVariablesMap);
    return () => {
      styleElRef.current?.remove();
      styleElRef.current = null;
    };
  }, [handleVariablesMap, cssVariablesMap]);

  return (
    <ThemeContext.Provider value={providerValue}>
      {children}
    </ThemeContext.Provider>
  );
}

export const useThemeContext = (): ThemeProviderProps =>
  useContext(ThemeContext);
