// packages/ui/src/vue/components/Button/Button.vue
<template>
  <MotionElement
    :class="mergedClass"
    v-bind="buttonProps as Record<string, unknown>"
  >
    <slot />
  </MotionElement>
</template>

<script lang="ts" setup>
import { get } from 'lodash-es';
import { motion } from 'motion-v';
import { twMerge } from 'tailwind-merge';
import { HTMLAttributes, computed, useAttrs } from 'vue';

import {
  type A11yButtonProps,
  buttonStyles,
  composeAnimationProps,
  createA11yButtonProps,
  cursorStyles,
} from '../../../lib';

export type ButtonProps = A11yButtonProps & {
  class?: HTMLAttributes['class'];
};

const buttonPropsAttributes = useAttrs() as ButtonProps;

const MotionElement = get(motion, ['button']);

const mergedClass = computed(() =>
  twMerge(
    buttonStyles(buttonPropsAttributes),
    cursorStyles(buttonPropsAttributes),
    buttonPropsAttributes.class,
  ),
);

const buttonProps = computed(() => ({
  ...createA11yButtonProps(buttonPropsAttributes),
  ...composeAnimationProps(buttonPropsAttributes),
}));
</script>

// packages/ui/src/react/components/Button/Button.tsx
import { get } from 'lodash-es';
import React from 'react';
import { twMerge } from 'tailwind-merge';

import {
  type A11yButtonProps as ButtonPropsBase,
  buttonStyles,
  composeAnimationProps,
  createA11yButtonProps,
  cursorStyles,
} from '../../../lib';
import { MotionElement } from '../motion';

export type ButtonProps = React.PropsWithChildren<ButtonPropsBase>;

export function Button(props: ButtonProps): React.ReactNode {
  return (
    <MotionElement
      as='button'
      className={twMerge(buttonStyles(props), cursorStyles(props))}
      type={get(props, ['type'], 'button')}
      {...createA11yButtonProps(props)}
      {...composeAnimationProps(props)}
    >
      {props.children}
    </MotionElement>
  );
}

Button.displayName = 'Button';
