// packages/ui/src/vue/components/motion/MotionElement.vue
<template>
  <component :is="Comp" v-bind="props as MotionProps" />
</template>

<script setup lang="ts">
import { motion } from 'motion-v';
import type { MotionProps } from 'motion-v';
import { computed } from 'vue';

type MotionElementProps<T extends keyof HTMLElementTagNameMap = 'div'> =
  MotionProps<T, HTMLElementTagNameMap[T]> & {
    as?: T;
  };

const props = defineProps<MotionElementProps>();

const Comp = computed(() => motion[props.as || 'div']);
</script>

// packages/ui/src/react/components/motion/MotionElement.tsx
import { type MotionProps, motion } from 'motion/react';
import React, { type FC, type ReactNode } from 'react';

export interface MotionElementProps<
  T extends keyof HTMLElementTagNameMap | FC = 'div',
> extends MotionProps {
  as?: T;
}

export function MotionElement<T extends keyof HTMLElementTagNameMap>({
  as,
  ...props
}: MotionElementProps<T> &
  Record<string | number | symbol, unknown>): ReactNode {
  const Component: FC<MotionElementProps<T>> = motion[as || 'div'];

  return <Component {...props} />;
}
