// packages/ui/src/components/motion/MotionElement.tsx
import { motion } from 'framer-motion';
import React from 'react';

import { type HTMLIntrinsicElements } from 'src/types';

export interface MotionElementProps {
  as?: HTMLIntrinsicElements;
}

export function MotionElement({
  as,
  ...props
}: MotionElementProps &
  Record<string | number | symbol, unknown>): React.ReactNode {
  const element = as || 'div';

  // @ts-expect-error type-mismatch between JSX HTML elements and Motion HTML elements
  const Component = motion[element];

  return <Component {...props} />;
}

// packages/ui/src/react/components/motion/MotionElement.tsx
import { type MotionProps, motion } from 'framer-motion';
import React, { type ReactNode } from 'react';

import { type HTMLIntrinsicElements } from 'src/lib/domain/types';

export interface MotionElementProps<T extends HTMLElement> extends MotionProps {
  as?: HTMLIntrinsicElements;
  ref?: React.Ref<T | null>;
}

export function MotionElement<T extends HTMLElement>({
  as,
  ref,
  ...props
}: MotionElementProps<T> &
  Record<string | number | symbol, unknown>): ReactNode {
  const element = as || 'div';

  // @ts-ignore type-mismatch between JSX HTML elements and Motion HTML elements
  const Component = motion[element];

  return <Component ref={ref} {...props} />;
}
